# Generated by Django 4.2.4 on 2023-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_next_id_post_prev_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='next_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='다음 단어 ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prev_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='이전 단어 ID'),
        ),
    ]
